"""dev_migration

Revision ID: e091029440fd
Revises: ce740692af1e
Create Date: 2024-12-14 21:26:20.610955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e091029440fd'
down_revision = 'ce740692af1e'
branch_labels = ()
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("city_locations") as batch_op:
        batch_op.alter_column('latitude',
                   existing_type=sa.DECIMAL(precision=8, scale=7),
                   type_=sa.DECIMAL(precision=9, scale=6),
                   existing_nullable=True)
        batch_op.alter_column('longitude',
                   existing_type=sa.DECIMAL(precision=8, scale=7),
                   type_=sa.DECIMAL(precision=9, scale=6),
                   existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("city_locations") as batch_op:
        batch_op.alter_column('longitude',
                   existing_type=sa.DECIMAL(precision=9, scale=6),
                   type_=sa.DECIMAL(precision=8, scale=7),
                   existing_nullable=True)
        batch_op.alter_column('latitude',
                   existing_type=sa.DECIMAL(precision=9, scale=6),
                   type_=sa.DECIMAL(precision=8, scale=7),
                   existing_nullable=True)
    # ### end Alembic commands ###
