"""dev_migration

Revision ID: 50165827d9c2
Revises: e091029440fd
Create Date: 2025-02-28 14:12:22.088347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50165827d9c2'
down_revision: Union[str, None] = 'e091029440fd'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_permission_id', 'ab_permission_view', ['permission_id'], unique=False)
    op.create_index('idx_view_menu_id', 'ab_permission_view', ['view_menu_id'], unique=False)
    op.create_index('idx_permission_view_id', 'ab_permission_view_role', ['permission_view_id'], unique=False)
    op.create_index('idx_role_id', 'ab_permission_view_role', ['role_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_role_id', table_name='ab_permission_view_role')
    op.drop_index('idx_permission_view_id', table_name='ab_permission_view_role')
    op.drop_index('idx_view_menu_id', table_name='ab_permission_view')
    op.drop_index('idx_permission_id', table_name='ab_permission_view')
    # ### end Alembic commands ###
